Create Java_interview_question
OOP	 	What is an object
	 	What is a class
	 	Mention 4 of the principals of Object Oriented Paradigm OOP
	 	What is Inheritance
	 	What is Abstraction
	 	What is Encapsulation
	 	What is Polymorphism
	 	Provide a basic example of Polymorphism
	 	How many ways exist to achieve Polymorphism?
	 	What is the State and Behavior of an Object
	 	Difference between Stateless and Stateful
	 	SOLID Principles
Java Basics	 	Java supports pass by value or pass by reference
	 	Enumerate and explain the access modifiers that exist in Java
	 	Difference between private vs protected
	 	What is the difference between protected and default
	 	What is static keyword for?
	 	What is a static method
	 	Why static methods cannot access non static variables or methods?
	 	What is static class?
	 	What is the difference between static and instance methods?
	 	What is difference between static block and the init block?
	 	What is the final keyword for
	 	What is Overloading
	 	What is Overriding
	 	Type Erasure
	 	Covariant throws,
	 	Difference between Interface and Abstract Class
	 	Difference between break and continue
	 	Difference between StringBuffer and StringBuilder
	 	Difference between String and StringBuilder
	 	What is the top level class in Java
	 	What the hashcode method is
	 	What does inmutable mean
	 	Create an immutable version based on a regular class
	 	What is a memory leak
	 	What is the difference between “==” and “equals()” in String objects
	 	What is the default implementation for equals()
	 	What is the StringPool
	 	What is the difference between final, finally and finalize() in Java?
Inmutable	 	What is an immutable class?
	 	How to create an immutable class?
	 	Immutable objects are automatically thread-safe –true/false
	 	What are the advantages of immutability?
Serialization	 	What is Serialization?
	 	What is use of serialVersionUID?
	 	What is the need of Serialization?
	 	Do we need to implement any method of Serializable interface to make an object serializable?
	 	What happens if the object to be serialized includes the references to other serializable objects?
	 	What happens if an object is serializable but it includes a reference to a non-serializable object?
	 	What is a transient variable?
	 	What will be the value of transient variable after de-serialization?
	 	What is the purpose of implementing the writeObject() and readObject() method?
Exception Handling	 	What is an Exception?
	 	Exceptions are defined in which java package?
	 	How are the exceptions handled in java?
	 	What is checked exception?
	 	What is Runtime Exception or unchecked exception?
	 	What is difference between Error and Exception?
	 	What is difference between ClassNotFoundException and NoClassDefFoundError?
	 	Is it valid to have a try block without catch or finally?
	 	Explain the try | catch | finally statement
	 	Is an empty catch block legal?
	 	Does the finally block always execute?
	 	Try-catch with resources
	 	What is throw keyword?
	 	What is use of throws keyword?
	 	Difference between throw and throws in java
Threads	 	What are the advantages or usage of threads?
	 	What are the two ways of creating thread?
	 	What are the different states of a thread's lifecycle?
	 	What does thread safe means?
	 	What is synchronized statement for?
	 	What is the difference when the synchronized keyword is applied to a static method or to a non static method?
	 	What is Volatile
	 	What is the difference between yield() and sleep()?
	 	What is the difference between wait() and sleep()?
	 	What is difference between notify() and notfiyAll()?
	 	What happens when start() is called?
	 	How many locks does an object have?
	 	When does deadlock occur and how to avoid it?
	 	What is thread starvation?
	 	What is a Race Condition?
Collections	 	What is difference between an ArrayList and a vector?
	 	How can an Arraylist be synchronized without using Vector?
	 	If an Employee class is present and its objects are added in an arrayList. Now I want the list to be sorted on the basis of the employeeID of Employee class. What are the steps?
	 	What is difference between a HashMap and a HashTable?
	 	How to navigate throug a map
	 	Sort a list
	 	What are the classes implementing the List interface?
	 	What is difference between List and a Set?
	 	What is difference between Arrays and ArrayList ?
	 	When to use ArrayList or LinkedList ?
	 	What are advantages of iterating a collection using iterator?
	 	What is a ConcurrentHashMap ?
	 	How to sort a list in reverse order?
	 	Can a null element be added to a Treeset or HashSet ?
	 	How to make a List (ArrayList, Vector, LinkedList) read only ?
	 	What is identityHashMap
	 	What is WeakHashMap
Garbage Collection	 	Which part of the memory is involved in Garbage Collection? Stack or Heap?
	 	What is responsiblity of Garbage Collector?
	 	Is garbage collector a dameon thread?
	 	How is Garbage Collection managed?
	 	When does an object become eligible for garbage collection?
	 	What are the different ways to make an object eligible for Garbage Collection when it is no longer needed?
	 	Can the Garbage Collection be forced by any means?
	 	How can the Garbage Collection be requested?
	 	What is the purpose of overriding finalize() method?
	 	How many times does the garbage collector calls the finalize() method for an object?
Nested Classes	 	What is an inner class?
	 	What are the different types of inner classes?
	 	What is static member class?
	 	What are non static inner classes?
	 	What is a member class
	 	What is a method local class
	 	What is an anonymous inner class
Annotations	 	What is Java Annotations?
	 	Annotations were introduced with which version of Java
	 	Which is the Parent Class of Annotation class?
	 	What is the package name for Annotation class?
	 	What are few of the Annotations pre defined by Java?
	 	What are meta Annotations ?
	 	Name few meta-annotations ?
	 	How to create a basic Annotation?
	 	How to define an annotation is only applicable to methods and fields?
Enums	 	What is an Enum type?
	 	Can Enum implement interface in Java?
	 	Can we extend an Enum?
	 	Can we create instance of Enum outside of Enum itself? If Not, Why?
	 	Can we declare Constructor inside Enum in Java?
	 	What does ordinal() method do in Enum?
Generics	 	What is Generics in Java?
	 	What is type erasure
	 	How do you declare a Generic Class?
	 	Can you pass List<String> to a method which accepts List<Object>
Design Patterns	 	Creational, Estructural, Behaivour
 	 	Singleton
 	 	Factory
 	 	 
Testing	 	Junit, Mockito, Selenium
Control Version	 	Svn, Git
 	 	Branches, Tags
Build Tools	 	Maven, Ant, Gradle, Jekin